package org.seattlego.eggplant.forms;

import java.awt.Color;
import javax.swing.JPanel;
import org.seattlego.eggplant.interfaces.ITournament;

/**
 *
 * @author Topsy
 */
public class MainWindow extends javax.swing.JFrame {

    
    private final Color SETUP = new Color( 238, 255, 238 );
    private final Color PREP = new Color( 255, 238, 255 );
    private final Color RUN = new Color( 255, 255, 238  );
    
    private ITournament tournament;
    
    private TournamentPane tp;
    
    private TournamentSettings tournamentSettings;
    private PlayersManager playersManager;
    private PairingsManager pairingsManager;
    private Results results;
    private Standings standings;
    private Bands bands;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        
    
        /*
         * Changing the default LAF settings does not change the fonts in the 
         * editor which defeats the purpose of using a GUI editor.
        // Tweak the default LAF font settings.
        try {
            Font oldLabelFont = UIManager.getFont("Label.font");
            Font newDefaultFont = oldLabelFont.deriveFont( Font.PLAIN, 11 );
            UIManager.put("Label.font", newDefaultFont );
            UIManager.put("Button.font", newDefaultFont );
        } catch ( Exception ex ) {
            Logger.getLogger( MainWindow.class.getName() ).log( Level.WARNING, "Unable to change LAF default fonts.", ex );
        }
        //
        * 
        */
        
        initComponents();
        init();
        
        tp = new TournamentPane();
        tp.setVisible( true );
        topPanel.add( tp );
        topPanel.revalidate();
        
        tournamentSettings = new TournamentSettings();
        tournamentSettings.setVisible(true);
        settingsPanel.add( tournamentSettings );
        
        playersManager = new PlayersManager();
        playersManager.setVisible( true );
        playersPanel.add( playersManager );
        
        bands = new Bands();
        bands.setVisible(true);
        bandsPanel.add( bands );
        
        pairingsManager = new PairingsManager();
        pairingsManager.setVisible( true );
        gamesPanel.add( pairingsManager );
        
        results = new Results();
        results.setVisible( true );
        resultsPanel.add( results );
        
        standings = new Standings();
        standings.setVisible( true );
        standingsPanel.add( standings );
        
        
        // Color code the tabs!
        jMainPane.setBackgroundAt( 0, SETUP );
        jMainPane.setBackgroundAt( 1, PREP );
        jMainPane.setBackgroundAt( 2, PREP );
        jMainPane.setBackgroundAt( 3, RUN );
        jMainPane.setBackgroundAt( 4, RUN );
        jMainPane.setBackgroundAt( 5, RUN );
        //
        
    }
    
    private void init() {
        //jMainPane.setUI( new CustomTabbedPaneUI() );
    }
    
    /*
     * Pass tournament reference to all sub-forms.
     */
    public void setTournament( ITournament tourney ) {
        tournament = tourney;
        
        tp.setTournament( tourney );
        
        tournamentSettings.setTournament( tourney );
        playersManager.setTournament( tourney );
        bands.setTournament( tourney );
        pairingsManager.setTournament( tourney );
        results.setTournament( tourney );
        standings.setTournament( tourney );
        
        
    }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        jMainPane = new javax.swing.JTabbedPane();
        settingsPanel = new javax.swing.JPanel();
        playersPanel = new javax.swing.JPanel();
        bandsPanel = new javax.swing.JPanel();
        gamesPanel = new javax.swing.JPanel();
        resultsPanel = new javax.swing.JPanel();
        standingsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Eggplant");
        setPreferredSize(new java.awt.Dimension(1000, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        topPanel.setPreferredSize(new java.awt.Dimension(920, 100));
        topPanel.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(topPanel, java.awt.BorderLayout.NORTH);

        jMainPane.setBackground(new java.awt.Color(238, 238, 238));
        jMainPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jMainPane.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jMainPane.setMinimumSize(new java.awt.Dimension(800, 600));
        jMainPane.setPreferredSize(new java.awt.Dimension(800, 600));
        jMainPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jMainPaneStateChanged(evt);
            }
        });

        settingsPanel.setLayout(new java.awt.GridLayout(1, 0));
        jMainPane.addTab("Settings", settingsPanel);

        playersPanel.setLayout(new java.awt.GridLayout(1, 0));
        jMainPane.addTab("Players", playersPanel);

        bandsPanel.setLayout(new java.awt.GridLayout(1, 0));
        jMainPane.addTab("Bands", bandsPanel);

        gamesPanel.setLayout(new java.awt.GridLayout(1, 0));
        jMainPane.addTab("Games", gamesPanel);

        resultsPanel.setLayout(new java.awt.GridLayout(1, 0));
        jMainPane.addTab("Results", resultsPanel);

        standingsPanel.setLayout(new java.awt.GridLayout(1, 0));
        jMainPane.addTab("Standings", standingsPanel);

        getContentPane().add(jMainPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMainPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jMainPaneStateChanged
        
        
        JPanel selectedTab = (JPanel) jMainPane.getSelectedComponent();
        if ( selectedTab.getComponents().length > 0 ) {
            EggplantForm activeForm = (EggplantForm) selectedTab.getComponents()[0];
            activeForm.updateControls();
        }
        
        
        //selectedTab.setFont( selectedTab.getFont().deriveFont( Font.BOLD ) );
        
    }//GEN-LAST:event_jMainPaneStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if ( tp.saveCurrentTournament() ) {
         System.exit( 0 );
        }

    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bandsPanel;
    private javax.swing.JPanel gamesPanel;
    private javax.swing.JTabbedPane jMainPane;
    private javax.swing.JPanel playersPanel;
    private javax.swing.JPanel resultsPanel;
    private javax.swing.JPanel settingsPanel;
    private javax.swing.JPanel standingsPanel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables

}
